"""empty message

Revision ID: 206e1216445f
Revises: 7f4899dcf2b8
Create Date: 2024-11-14 19:22:42.270208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206e1216445f'
down_revision = '7f4899dcf2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
