"""empty message

Revision ID: 7f4899dcf2b8
Revises: 2a92bcdd7566
Create Date: 2024-11-12 22:10:30.014162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f4899dcf2b8'
down_revision = '2a92bcdd7566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabrica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fabrica_id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['fabrica_id'], ['fabrica.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=False))
        batch_op.drop_column('cantidad_disponible')
        batch_op.drop_column('ubicacion_almacen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion_almacen', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('cantidad_disponible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('cantidad')

    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.drop_column('nombre')

    op.drop_table('celular')
    op.drop_table('user')
    op.drop_table('fabrica')
    # ### end Alembic commands ###
